### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by JumperPunk** [Shizcow/dmenu-rs#2]
Are there any plans to support wayland natively?
I realize this may be out of scope, as dmenu does not support it.

**Comment by Shizcow** [comment]
Because dmenu-rs (and source dmenu) uses native X bindings for all rendering, adding wayland support would require rewriting upwards of 80% of the source code. Although it's not out of the question, there are several other things I'd like to complete first.

Closing as wontfix for the forseeable future.

**Comment by Shizcow** [comment]
Currently, I'm completely rewriting the render engine with xcb/xkb/cairo/pango, as apposed to xlib. During this process I plan to make every step of rendering modular. As xkb is well supported on wayland, and cairo and pango __appear__ to be supported, I'd be willing to put in some extra effort to make this run on wayland.

The largest portion of work here will be switching from xcb to some wayland library.

**Comment by Shizcow** [comment]
**Help Wanted**: Recommendations for wayland libraries? Anything working in rust? Similar projects already completed?

It will take me a bit to finish the backend here before being able to start wayland -- any information gathered in the meantime will be appreciated.

**Comment by asdf8dfafjk** [comment]
No matter how you rewrite it in your xlib -> xcb port, this program would be > 80% GUI and < 20% logic, and thus IMHO a wayland port would be a waste of time. (I also think so is xcb port but thats your choice). 

That said, I believe there is only 1 under-development rust wayland client library under, github.com/smithay . (surprisingly couldn't find any c-ffi bindigns to other libs ... ). There are some c libraries too.

**Comment by Shizcow** [comment]
Time isn't an issue for me. This project has been dead for a while anyway, but I do recognize the value of not bloating the to-do list.

C libraries are fine but I'm not keen on working with bindgen again -- it's just annoying.

**Comment by asdf8dfafjk** [comment]
> dead for a while

I prefer the term "done". It's mature IMHO.

**Comment by Jemi** [comment]
I expect porting this to Cairo will make it vastly slower with no appreciable benefit. Pango could be useful but I'm not sure how it would affect speed. Pango can use XFT as a backend. Dmenu-rs should be fast even on an IBM AT.
