### ISSUE TITLE
Font Line Height

### ISSUE THREAD

**Issue by ibrokemypie** [Shizcow/dmenu-rs#22]
When changing the font size in dmenu, the height of the dmenu bar grows/shrinks to accommodate the new size, however this doesnt happen in dmenu-rs, the menu stays the same height wither with expanded or condensed text in it.

**Comment by ibrokemypie** [comment]
I guess this is related to #15, though i think itd make sense for font size to act as normal, and the menu height option to override it

**Comment by Shizcow** [comment]
I'm having trouble replicating this issue. Can you give specific commands to replicate?

**Comment by ibrokemypie** [comment]
Yep that seems to have solved it!
