### ISSUE TITLE
prompt not working with calc plugin

### ISSUE THREAD

**Issue by brandonsandoval** [Shizcow/dmenu-rs#4]
Hello,

When using "-p" option to display a prompt while using --calc plugin, the prompt is used as part of the calculation, when really the prompt should be ignored in the calculator and used only for display purposes.

Examples:
dmenu_run --calc -p "xyzzz"
calculator breaks

dmenu_run --calc -p "2*2"
calculator multiples everything by "4" as if "(2*2)" was typed first.

**Comment by Shizcow** [comment]
I've pushed out a temporary fix to which makes `--prompt` and `--calc` conflict to address this issue.

The next step is supporting a longer-form description of flags in `plugin.yml` to make these things more clear. Once this is done, this issue will be closed.

**Comment by Shizcow** [comment]
`long_help` is now supported for flags, integrated with manpage generation. A description of usage for `--calc` has been added to make controls more apparent to the end user.
