### ISSUE TITLE
warning: no locale support

### ISSUE THREAD

**Issue by drewauff** [Shizcow/dmenu-rs#40]
getting this error first time and every time I run dmenu

**Comment by Shizcow** [comment]
Can you give a more thorough description of what error you get? Or just post the command error output?

**Comment by drewauff** [comment]
that is the only output I get...

**Comment by drewauff** [comment]
I tried this, fwiw, export "LC_CTYPE=en_AU.UTF-8" 

but no good

**Comment by Shizcow** [comment]
This is sounding like a system issue. Did you run `genlocale` (or your distros equivalent) after setting the correct locale files on your system? X or fontconfig will spit out a similar error if you have not.

**Comment by drewauff** [comment]
been trying a few things , now getting an added error message "cannot open display"

**Comment by Shizcow** [comment]
Looks like `$DISPLAY` isn't set. Are you even running X? This doesn't support Wayland or anything not Linux (apparently it works on macOS with xquartz, untested).

**Comment by drewauff** [comment]
yeah trying to get it running on xquartz

**Comment by Shizcow** [comment]
Ok can you get source dmenu to work?

**Comment by drewauff** [comment]
er..seems xquartx has decided not to play nice...

**Comment by drewauff** [comment]
ok xquartx all good, but still same error

**Comment by Shizcow** [comment]
You've posted multiple errors so far. Can I get exact terminal output from running the following command: `echo 1 | dmenu`? If there isn't much to go off of, please run it in gdb and provide a backtrace (don't forget stdin).

**Comment by drewauff** [comment]
warning: no locale support
cannot open display


that's all I get

**Comment by Shizcow** [comment]
Considering that this is an xquartz issue, closing as "not my problem."
