### ISSUE TITLE
File names expected instead of path for the `-l` option

### ISSUE THREAD

**Issue by maheshbansod** [Shizcow/dmenu-rs#53]
Hi, regarding the issue discussed in PR #52, I noticed today that the actual difference is with the `-l` option of stest, though, in the `man` , it's just `Test the contents of a directory given as an argument.` and no information about filepaths vs filename.

Original stest:
```
 $ ./stest -l .
README
config.def.h
util.o
drw.c
stest.o
dmenu.c
drw.h
arg.h
drw.o
dmenu.o
dmenu.1
stest.c
dmenu
dmenu_run
config.mk
util.h
config.h
util.c
dmenu_path
stest
Makefile
LICENSE
stest.1
```

dmenu-rs stest:
```
 $ ./target/stest -l .
./.gitignore
./target
./makefile
./src
./config.mk
./.git
./README.md
./LICENSE
```

i.e. apparently the original `stest` has a different behaviour than usual with the `-l` option - the original stest does not print the path, just the filename. And this is affecting the `dmenu_path` script causing full paths in `dmenu_run`.

Also, probably unrelated but the outputs of   
`stest .` and `stest ./*` are different for original and dmenu-rs.
in case of the original, there is no output ( which actually feels weird for the `./*` case).

**Comment by Shizcow** [comment]
Ahh, the `-l` makes sense. I checked the behavior and your explanation all looks correct. Looks like we just need the contents of your old PR + the command line switch.

Now to see which one of us finds the time to fix this first :+1:

**Comment by maheshbansod** [comment]
I'm on it. :)
