### ISSUE TITLE
Add new release tag?

### ISSUE THREAD

**Issue by Lieunoir** [Shizcow/dmenu-rs#59]
The current AUR package is set to use the last release tag, which currently has a faulty makefile thus making the installation fail. Adding a new tag could fix that

**Comment by Shizcow** [comment]
Thanks for bringing this to my attention. I've added a new release tag and updated the AUR packages. This should work; let me know if you're still running into issues.

**Comment by Lieunoir** [comment]
This worked for me! Than you very much!
