### ISSUE TITLE
Bytes and bits all get converted to bits

### ISSUE THREAD

**Issue by brandonsandoval** [Shizcow/dmenu-rs#6]
Not sure if this is expected behavior, but typing just "5 bytes" shows up as "40 bit" but there shouldn't be any conversion yet as I haven't typed "..to"

Similarly if I do "800GB" I get "6.4 terrabit" which is an odd conversion when I believe it should display it in its original units, i.e. "800GB" = 800 Gigabyte.?

**Comment by Shizcow** [comment]
Because `calc-mode` uses `rink-rs` for processing queries, this is out of the scope of this project. If you believe this is a legitimate issue, file it on the [rink-rs repo](https://github.com/tiffany352/rink-rs).
