### ISSUE TITLE
dmenu not displayed on some empty monitors

### ISSUE THREAD

**Issue by brandonsandoval** [Shizcow/dmenu-rs#9]
In a multi-monitor setup (I'm using 3), if the active monitor has no open windows, the dmenu appears to always launch to the first monitor, rather than the current active monitor, I have to open at least 1 window, i.e. terminal, to get the dmenu to show up on the same monitor. dmenu does not have this issue. I am using i3wm. Thanks.

**Comment by Shizcow** [comment]
I am able to replicate this issue. However, `community/dmenu` also has this issue for me, but only sometimes.

I'm unsure how difficult this will be to fix, but I'll look into it.

**Comment by Shizcow** [comment]
This issue has been resolved. It was causes by the following bit of code:
```rust
for i in 0..n {
    if intersect(x, y, 1, 1, info.offset(i as isize)) != 0 {
	break;
    }
}
```
`i` is a local variable that's intended to be overwritten. The loop invokes shadowing rules, leaving local `i` untouched. Targeting for 5.2.3 release.
